2021-11-1
kinest1997/Minime pull request #1
Opened 2021-11-01 14:30 UTC by kinest1997

완료!
오류 수정하느라 40분 잡아먹었네

2021-11-01 22:48 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +    let bigStackview = UIStackView()
```suggestion
    let bigStackView = UIStackView()
```

2021-11-01 22:49 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +    let resetButton = UIButton()
```suggestion
```
아무런 액션도 없다면 굳이 넣을 필요가?

2021-11-01 22:51 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +    let midStackView = UIStackView()
상단에 middleStackView가 있어서 용도 구분이 어려움.
숫자를 담는 stack view와 상단의 display 역할을 하는 부분으로 나누거나,
StackView가 포함하는 arrangedView들의 역할을 고려한 네이밍으로 수정하는 것이 좋을 듯

2021-11-01 22:53 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +                print("템프어레이",self.myAnswer)
```suggestion
```
테스트 용도의 print는 지워도 무방할 듯

2021-11-01 22:53 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +            let num = (keypadArray.firstIndex(of: $0)! + 1)
또는 각 버튼마다 `.tag(Int)`를 부여할 수 있음

2021-11-01 22:55 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +                        alert.addAction(okButton)
이 부분만 빼서 presentAlert() 형태의 함수로 빼도 좋을 듯

2021-11-01 23:00 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +        var mySetAnswer: Set<Int> = []
사용자가 입력한 값을 아무런 설명 없이 Set으로 걸러주는 것은 좋지 않음.
암묵적인 룰로 중복된 숫자는 입력할 수 없다는 규칙을 두고 사용자가 122, 111 이런식으로 입력은 할 수 있게 해놓는다면 버그처럼 보일 것임.
- 중복을 허용하거나(단지 답을 맞추기 어려울 뿐)
- 3개의 숫자를 누를 때까지는 한번 누른 버튼을 비활성화 시키거나
- 중복된 버튼을 눌렀을 때 상태 라벨에 표시해주기(중복해서 숫자를 입력할 수 없다) 
이런식으로 사용자의 액션과 입력되는 데이터가 상이하지 않도록 처리해야 함

2021-11-01 23:01 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +        let starting = UIAction {[weak self]_ in
```suggestion
        let starting = UIAction { [weak self] _ in
```

2021-11-01 23:03 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +        let keypadArray = [oneButton, twoButton, threeButton, fourButton, fiveButton, sixButton, sevenButton, eightButton, nineButton]
layout 함수 안에서 keypadArray 라는 상수는 한번밖에 안쓰여서 선언하지 않고 그냥 같다 붙여도 무방할 듯 합니다

2021-11-01 23:03 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +            $0.tag = sequence
이건 무슨 용도일까?

2021-11-01 23:06 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +
```suggestion
```

2021-11-01 23:07 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +        resetButton.backgroundColor = .systemBrown
이건 layout 보다는 attribute 함수에 적합한 내용일 듯

2021-11-01 23:07 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +        midStackView.axis = .horizontal
이건 layout 보다는 attribute 함수에 적합한 내용일 듯

2021-11-01 23:07 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +            $0.distribution = .fillEqually
이건 layout 보다는 attribute 함수에 적합한 내용일 듯

2021-11-01 23:07 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +            $0.distribution = .fillEqually
이건 layout 보다는 attribute 함수에 적합한 내용일 듯

2021-11-01 23:09 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +        print(myAnswer)
테스트용 print 굿바이~
```suggestion
```

2021-11-01 23:10 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +            }else if myAnswer.contains(answer[i]) {
```suggestion
            } else if myAnswer.contains(answer[i]) {
```

2021-11-01 23:10 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +            }else { outCount += 1}
```suggestion
            } else { 
                outCount += 1
            }
```

2021-11-01 23:11 UTC, fimuxd commented on baseball/baseball/MainViewController.swift
> +
```suggestion
```

2021-11-01 23:12 UTC, fimuxd requested changes
Develop 브랜치를 Main으로 PR 하다니..ㅠㅠ
Develop 브랜치에서 별도의 branch를 빼서 develop으로 PR 남겼어야 했음...

별도로 코멘트 남긴 것들 수정/답변 남겨주세요

2021-11-02 01:00 UTC, kinest1997 commented on baseball/baseball/MainViewController.swift
> +            $0.tag = sequence
태그를 붙여주기 위해..?

2021-11-02 01:22 UTC, kinest1997 commented on baseball/baseball/MainViewController.swift
> +            $0.tag = sequence
태그가 아니라 숫자 키패드에 123 붙여주려고 한거였넹

2021-11-02 02:45 UTC, fimuxd commented
잘못된 브랜치 작업으로 인한 잘못된 PR

2021-11-02 02:45 UTC, closed without merging