Add filter
kinest1997/Minime pull request #13
Opened 2021-11-25 08:08 UTC by kinest1997

일단 중간 수정본

2021-11-26 11:38 UTC, fimuxd commented on Cocktail/Cocktail Widget/Cocktail_SmallView.swift
> +//}
되살리던지 지우던지

2021-11-26 11:38 UTC, fimuxd commented on Cocktail/Cocktail Widget/Cocktail_Widget.swift
> +        let entry = CocktailEntry(date: Date(), configuration: getWidgetRecipe().randomElement()!)
! 가 과연 최선일까!

2021-11-26 11:39 UTC, fimuxd commented on Cocktail/Cocktail Widget/Cocktail_Widget.swift
> +        let entry = CocktailEntry(date: Date(), configuration: getWidgetRecipe().randomElement()!)
(최선이 아니니 default cocktail을 두는 쪽으로 변경

2021-11-26 11:40 UTC, fimuxd commented on Cocktail/Cocktail Widget/Cocktail_Widget.swift
> +        }
별개의 subView 형태로 만들었던 것 같은데 다시 되돌려놓으셨넹

2021-11-26 11:41 UTC, fimuxd commented on Cocktail/Cocktail Widget/Cocktail_Widget.swift
> +        .configurationDisplayName("Test")
진짜 DisplayName을 테스트로 할게 아니라면 수정할 것

2021-11-26 11:41 UTC, fimuxd commented on Cocktail/Cocktail Widget/Cocktail_Widget.swift
> +        .description("babo")
마찬가지

2021-11-26 11:41 UTC, fimuxd commented on Cocktail/Cocktail Widget/Cocktail_Widget.swift
> +//}
살리거나 지우거나

2021-11-26 11:41 UTC, fimuxd commented on Cocktail/Cocktail/CocktailStruct.swift
> +protocol CocktailCondition {
누가 쓴 코드랑 비슷하군요 :)

2021-11-26 11:42 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
> +    //    guard let documentURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.heesung.cocktail")?.appendingPathComponent("Cocktail.plist") else { return }
앞으로 이런건 commit 단계부터 정리하고 올릴 것
삭제하시오

2021-11-26 11:42 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
> +    do { print(documentURL)
삭제

2021-11-26 11:42 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
> +    do { print(documentURL)
불필요한 print 삭제하고 올릴 것

2021-11-26 11:43 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
> +            print("도큐먼트에서 앱그룹으로 복사함")
코드 테스트 단에서의 각종 print들, 앞으로도 꼭 필요한게 아니면 정리할 것

2021-11-26 11:43 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
> +
print 삭제
불필요한 줄 띄어쓰기 삭제

2021-11-26 11:43 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
> +
```suggestion
```

2021-11-26 11:43 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
> +
앞으로 이런거 안 봐줄 예정

2021-11-26 11:44 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
> +    //이미지 크기 변환 해주는것
이 아이는 주석을 /// 이렇게 치고 작성하면 해당 함수 설명에 뜨게 됨

2021-11-26 11:44 UTC, fimuxd commented on Cocktail/Cocktail/MainViewController.swift
> +
```suggestion
```

2021-11-26 11:45 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/CocktailDetailViewController.swift
> +
```suggestion
}
```
🔥

2021-11-26 11:46 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/CocktailRecipeViewController.swift
> +            [1, 0, 2, 3, 4, 5].forEach {
이 부분 내가 작성한거지만, 굳이 왜 함수를 Base 부터 둔 것임? 
순서대로 alcohol 부터 파라미터 뒀으면 (0...5) 이렇게 작성도 가능한데..
매우 찝찝함. 수정 바람

2021-11-26 11:47 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +    var alcohol: Cocktail.Alcohol?
굿

2021-11-26 11:50 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +    let imagePickerController = UIImagePickerController()
UIImagePicker를 사용헀군..
작년 WWDC에서 UIImagePicker를 모던하게 대체한 PHPicker를 발표하였음.
어차피 minimum  target이 iOS15로 되어있으니 PHPicker로 리팩토링 할 것.
(귀찮고 싫겠지만 하시오. UIImagePicker는 구시대의 유물이 될 것임

2021-11-26 11:50 UTC, kinest1997 commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +    let imagePickerController = UIImagePickerController()
오케이......

2021-11-26 11:51 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +        guard let craft = craft, let glass = glass, let baseDrink = baseDrink, let alcohol = alcohol, let color = color, let drinkType = drinkType, let ingredients = ingredients else { return present
```suggestion
        guard let craft = craft, 
        let glass = glass, 
        let baseDrink = baseDrink, 
        let alcohol = alcohol, 
        let color = color, 
        let drinkType = drinkType, 
        let ingredients = ingredients else { 
        return presentJustAlert(title: "Hold on".localized, message: "선택안한게 있어!")
        }
```
되도록 이렇게 읽기 좋은 코드로

2021-11-26 11:51 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +
```suggestion
```

2021-11-26 11:51 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +            DispatchQueue.global(qos: .utility).async {reloadwidgetData()}
```suggestion
            DispatchQueue.global(qos: .utility).async { reloadwidgetData() }
```

2021-11-26 11:52 UTC, fimuxd commented on Cocktail/Cocktail/ko.lproj/Localizable.strings
> +"Write tips" = "팁도좀 적어";
ㅋㅋㅋㅋ 진심 이렇게 명령하는 앱을 만들거임?

2021-11-26 11:52 UTC, fimuxd requested changes
노노 아니되오

2021-11-26 11:53 UTC, kinest1997 commented on Cocktail/Cocktail/ko.lproj/Localizable.strings
> +"Write tips" = "팁도좀 적어";
잠시 해놓은것..!

2021-11-28 03:49 UTC, fimuxd approved these changes

2021-11-28 03:49 UTC, fimuxd commented on Cocktail/Cocktail/MyPlayground.playground/Contents.swift
> +
테스트용 pg라면 pr 올릴 때는 정리된 상태인 것이 좋을 듯

2021-11-28 04:38 UTC, kinest1997 commented on Cocktail/Cocktail/MyPlayground.playground/Contents.swift
> +
알겠습죠

2021-11-28 04:38 UTC, merged