Wish list
kinest1997/Minime pull request #17
Opened 2021-11-28 06:15 UTC by kinest1997

즐겨찾기 기능 업데이트

2021-11-28 06:45 UTC, fimuxd requested changes
즐겨찾기까지 추가하다니... 👍🏼

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
> +func getRecipe() -> [Cocktail] {
👍🏼

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
>      do {
```suggestion
    guard let documentURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.heesung.cocktail")?.appendingPathComponent("Cocktail.plist"), 
    let cocktailData = FileManager.default.contents(atPath: documentURL.path) else { return [] }
    do {
```

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/GlobalFunction.swift
> +    newRecipes.append(modifiedRecipe)
이렇게 하면 삭제된 위치에 들어가지 않고 그냥 append만 되는 것 같은데 의도한게 맞을까?
newRecipes.insert(at:)을 사용해야 하는 것이 아닐까

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/MyBadgeButton.swift
> +
```suggestion
```

굳이?

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/SceneDelegate.swift
> +
```suggestion
```

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/CocktailDetailViewController.swift
> +
```suggestion

```
이런 것도 commit 단에서 수정해서 불필요한 수정 기록되지 않도록 하는 것이 깔끔

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/CocktailDetailViewController.swift
> +
```suggestion
```
굳이?222

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/CocktailDetailViewController.swift
> +            guard let self = self, let cocktailData = self.cocktailData else { return }
```suggestion
            guard let self = self, 
            let cocktailData = self.cocktailData else { return }
```
guard 문에 복수의 optional 값을 처리할 때 구분해 주는 것이 가독성 측면에서 나음

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/CocktailDetailViewController.swift
> +            }
```suggestion
let hasWishList = self.cocktailData?.wishList == true
self.likeButton.setImage(UIImage(systemName: hasWishList ? "heart" : "heart.fill"), for: .normal)
var modifiedRecipe = cocktailData
modifiedRecipe.wishList = hasWishList ? false : true
updateRecipe(originRecipe: cocktailData, modifiedRecipe: modifiedRecipe, origin: self.originRecipe)
```
삼항조건연산자를 써서 이렇게 처리해도 깔끔할 듯
전체적인 로직은 동일하지만 조건에 따라서 일부 변수의 값이 달라지는 것이라면.

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/CocktailDetailViewController.swift
> +
```suggestion

```
역시..앞으로 commit 올릴 때부터, 단순하게 파일 선택하고 커밋메시지 추가해서 올리지말고
각 파일의 변경 내용을 확인할것

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/CocktailDetailViewController.swift
> +        }
```suggestion
        likeButton.setImage(UIImage(systemName: data.wishList == true ? "heart.fill" : "heart"), for: .normal)
```
이 부분도 역시 삼항조건으로 처리할 수 있을 듯

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AssistantViewController.swift
> +        wishListButton.addAction(UIAction(handler: { [weak self]_ in
```suggestion
        wishListButton.addAction(UIAction(handler: {[weak self] _ in
```
보통 이런식으로 인덴트

2021-11-28 06:45 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AssistantViewController.swift
> +        wishListButton.setTitle("즐겨찾기", for: .normal)
이제는 뷰에 새로운 string 추가할 때 localization을 고려해서 작성할 것

2021-11-28 09:04 UTC, kinest1997 commented on Cocktail/Cocktail/MyBadgeButton.swift
> +
자꾸 스냅킷을 못읽어서 이것저것 시도하다가 남은 잔재...!

2021-11-29 01:15 UTC, fimuxd requested changes
하나만 더

2021-11-29 01:15 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/CocktailDetailViewController.swift
> +updateRecipe(originRecipe: cocktailData, modifiedRecipe: modifiedRecipe, origin: self.originRecipe)
> 수정필!
여기 인덴트가 좀 이상한데 아마 내 코드 그대로 커밋해서 그런 것 같음

2021-11-30 02:26 UTC, fimuxd approved these changes

2021-11-30 06:35 UTC, merged