Developer account link
kinest1997/Minime pull request #24
Opened 2021-12-04 16:35 UTC by kinest1997

로그인, 로그아웃 추가. 로그인 하지않고 사용할수있게 함 그대신 좋아요랑 내가만든 레시피는 사용 해도 저장 안됨. 설정창 많이 만들어냄. 내 계정들로 연결되도록 하는 버튼 추가. 이제 내가 만든 레시피 편집하면 편집전 레시피가 남아있지 않음.

2021-12-05 01:56 UTC, fimuxd commented on Cocktail/Cocktail/FirstLaunch/ColorChoiceViewController.swift
> +    var myFavor: Bool = true
myFavor 역할이 좋아하는 색깔 선정임?
기본 값으로 true인 것이 맞을까?

2021-12-05 01:58 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/CocktailDetailViewController.swift
> +        //순서가 필요할까 아직 고민중이긴한데 일단 이대로 두겠음 .enumerated 를 사용할지 의견받는중
순서가 필요할 것 같음.
특히 사용자가 입력한 값에 대해서도 영향을 받는다면 순서를 보장하는 것이 사용자 입장에서 자연스러울 것임.

2021-12-05 01:59 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +        super.viewWillDisappear(animated)
deinit 시점해서 하는 것이 좋을 듯
이렇게 하면 해당 뷰에서 childView가 뜰 때 등 뷰가 그냥 가려졌을 때마다 계속 불릴거라서

2021-12-05 01:59 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +        //레이아웃을 이제 슬슬 꾸며야한다..
winter is coming....

2021-12-05 02:06 UTC, fimuxd requested changes
코멘트 확인해주세요. 

+ 로그인 없이도 사용할 수 있게 한 것은 좋습니다. 
+ 다만 그렇다면 내 술장에 접근이 아예 안되거나(탭 자체가 없거나) 또는 입력하려 할 때 로그인을 하라고 유도하는 것이 있으면 좋겠습니다.

2021-12-05 02:06 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +        //이부분 코드 점검 키보드 노티가 애매해짐. 5 이하일때 올릴필요는 없고 근데 칵테일 레시피가 5단계가 넘을일이..? 일단 보류
사용자의 행동은 항상 예측할 수 없기 때문에 어떤 조건을 단정하는 것은 유의해야함.
만약에 레시피 5단계를 넘을일이 현저하게 적다면 애초에 5단계 이상 입력하지 못하게 하는 것이 맞음.
어떤 규칙없이 허용해놓고 암묵적으로 개발자가 생각한 규칙을 남겨놓으면 사용자는 불쾌함을 느낄 수 밖에 없음

2021-12-05 02:06 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +        //아무것도 입력하지않고 엔터눌러서 키보드를 내리면 밑부분이 더 내릴수없는 상태로 살짝 잘리는데 다시 키보드 올렸다가 내리면 원상 복구됨, 이 버그는 어떻게 쳐리해야할지 감이안옴..
밑에 조건문 때문이지 않을까 싶은데..

2021-12-05 02:06 UTC, fimuxd commented on Cocktail/Cocktail/ViewControllers/SettingTableViewController.swift
> +    }
이렇게 하면 제대로 안꺼질 것 같은데.. 또한 RemoteNoti 뿐만 아니라 LocalNoti도 꺼줘야 함
사용자 입장에서는 알림 이라고 단일표현되지만 사실 뒷단에서는 알림을 보내는 방법이 여러개인 것임.
실제로 스위치가 켜져있던 걸 끄거나 그 반대로 헀을 때 사용자가 체감할 수 있게 변화하지 않음.
보통 알람을 껐다면 아이폰의 설정 -> 알림 -> 쉐이커 들어갔을 때 알림도 꺼져있어야 하는데 영향받지 않고 있음.

2021-12-05 07:36 UTC, kinest1997 commented on Cocktail/Cocktail/FirstLaunch/ColorChoiceViewController.swift
> +    var myFavor: Bool = true
이뷰를 칵테일 추천시에도 재활용 하기위해서 저 조건을 추가해둿음 만약 저게 true 라면 내 취향에 저장하는게 아니라 다른사람을 추천해줄땐 처음부터 띄울건데 그때 내 취향을 변경시키면 안되니까 저게 false 면 싱글톤안에 조건을 넣어서 앱 켜저있는동안만 잠시 활용하도록

2021-12-05 07:43 UTC, kinest1997 commented on Cocktail/Cocktail/ViewControllers/SettingTableViewController.swift
> +    }
어떻게 해야 적용이 될지 모르겠어서 아직 열심히 찾는중..

2021-12-05 10:16 UTC, kinest1997 commented on Cocktail/Cocktail/ViewControllers/HomeBar/AddMyOwnCocktailRecipeViewController.swift
> +        //이부분 코드 점검 키보드 노티가 애매해짐. 5 이하일때 올릴필요는 없고 근데 칵테일 레시피가 5단계가 넘을일이..? 일단 보류
다른가지에서 진행하겠읍니다...

2021-12-08 13:04 UTC, fimuxd approved these changes
3,228...... 3228!!!!

2021-12-08 13:23 UTC, merged